import type { Section } from "../types";

export const apiTemplate: Section[] = [
  {
    id: "section-1",
    title: "Introduction",
    slug: "introduction",
    pages: [
      {
        id: "page-1",
        title: "Overview",
        slug: "overview",
        purpose: "Explain what your API does and its capabilities",
        status: "empty",
        content: "",
      },
      {
        id: "page-2",
        title: "Base URL & Versioning",
        slug: "base-url-versioning",
        purpose: "Document API base URL and version strategy",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-2",
    title: "Authentication",
    slug: "authentication",
    pages: [
      {
        id: "page-3",
        title: "Getting API Keys",
        slug: "getting-api-keys",
        purpose: "Show how to obtain credentials",
        status: "empty",
        content: "",
      },
      {
        id: "page-4",
        title: "Authentication Methods",
        slug: "authentication-methods",
        purpose: "Document supported auth methods (API keys, OAuth, etc.)",
        status: "empty",
        content: "",
      },
      {
        id: "page-5",
        title: "Security Best Practices",
        slug: "security-best-practices",
        purpose: "Share security recommendations",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-3",
    title: "Endpoints",
    slug: "endpoints",
    pages: [
      {
        id: "page-6",
        title: "REST Resources",
        slug: "rest-resources",
        purpose: "Document all available endpoints",
        status: "empty",
        content: "",
      },
      {
        id: "page-7",
        title: "Request Format",
        slug: "request-format",
        purpose: "Explain request structure and headers",
        status: "empty",
        content: "",
      },
      {
        id: "page-8",
        title: "Response Format",
        slug: "response-format",
        purpose: "Document response structure and status codes",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-4",
    title: "Reference",
    slug: "reference",
    pages: [
      {
        id: "page-9",
        title: "Error Codes",
        slug: "error-codes",
        purpose: "List all possible error codes and meanings",
        status: "empty",
        content: "",
      },
      {
        id: "page-10",
        title: "Rate Limiting",
        slug: "rate-limiting",
        purpose: "Document rate limits and quotas",
        status: "empty",
        content: "",
      },
      {
        id: "page-11",
        title: "Webhooks",
        slug: "webhooks",
        purpose: "Explain webhook events and payload structure",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-5",
    title: "Guides",
    slug: "guides",
    pages: [
      {
        id: "page-12",
        title: "Quick Start",
        slug: "quick-start",
        purpose: "Get developers making their first API call",
        status: "empty",
        content: "",
      },
      {
        id: "page-13",
        title: "Code Examples",
        slug: "code-examples",
        purpose: "Provide examples in multiple languages",
        status: "empty",
        content: "",
      },
      {
        id: "page-14",
        title: "Common Patterns",
        slug: "common-patterns",
        purpose: "Show best practices for common use cases",
        status: "empty",
        content: "",
      },
    ],
  },
];
