import type { Section } from "../types";

export const applicationTemplate: Section[] = [
  {
    id: "section-1",
    title: "Getting Started",
    slug: "getting-started",
    pages: [
      {
        id: "page-1",
        title: "Welcome",
        slug: "welcome",
        purpose: "Welcome users and explain what the app does",
        status: "empty",
        content: "",
      },
      {
        id: "page-2",
        title: "Sign Up",
        slug: "sign-up",
        purpose: "Guide users through account creation",
        status: "empty",
        content: "",
      },
      {
        id: "page-3",
        title: "First Steps",
        slug: "first-steps",
        purpose: "Help users get started with basic features",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-2",
    title: "Core Features",
    slug: "core-features",
    pages: [
      {
        id: "page-4",
        title: "Feature Overview",
        slug: "feature-overview",
        purpose: "List and describe main features",
        status: "empty",
        content: "",
      },
      {
        id: "page-5",
        title: "Dashboard",
        slug: "dashboard",
        purpose: "Explain the main dashboard",
        status: "empty",
        content: "",
      },
      {
        id: "page-6",
        title: "Settings",
        slug: "settings",
        purpose: "Document settings and preferences",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-3",
    title: "How-To Guides",
    slug: "how-to-guides",
    pages: [
      {
        id: "page-7",
        title: "Common Tasks",
        slug: "common-tasks",
        purpose: "Show how to do everyday tasks",
        status: "empty",
        content: "",
      },
      {
        id: "page-8",
        title: "Tips & Tricks",
        slug: "tips-tricks",
        purpose: "Share productivity tips",
        status: "empty",
        content: "",
      },
      {
        id: "page-9",
        title: "Keyboard Shortcuts",
        slug: "keyboard-shortcuts",
        purpose: "List keyboard shortcuts for power users",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-4",
    title: "Account & Billing",
    slug: "account-billing",
    pages: [
      {
        id: "page-10",
        title: "Account Settings",
        slug: "account-settings",
        purpose: "Explain account management",
        status: "empty",
        content: "",
      },
      {
        id: "page-11",
        title: "Plans & Pricing",
        slug: "plans-pricing",
        purpose: "Describe subscription plans",
        status: "empty",
        content: "",
      },
      {
        id: "page-12",
        title: "Billing FAQ",
        slug: "billing-faq",
        purpose: "Answer common billing questions",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-5",
    title: "Support",
    slug: "support",
    pages: [
      {
        id: "page-13",
        title: "FAQ",
        slug: "faq",
        purpose: "Answer frequently asked questions",
        status: "empty",
        content: "",
      },
      {
        id: "page-14",
        title: "Troubleshooting",
        slug: "troubleshooting",
        purpose: "Help users solve common problems",
        status: "empty",
        content: "",
      },
      {
        id: "page-15",
        title: "Contact Us",
        slug: "contact-us",
        purpose: "Show how to get help",
        status: "empty",
        content: "",
      },
    ],
  },
];
