import type { Section } from "../types";

export const designSystemTemplate: Section[] = [
  {
    id: "section-1",
    title: "Getting Started",
    slug: "getting-started",
    pages: [
      {
        id: "page-1",
        title: "Overview",
        slug: "overview",
        purpose: "Introduce your design system and its goals",
        status: "empty",
        content: "",
      },
      {
        id: "page-2",
        title: "Installation",
        slug: "installation",
        purpose: "Show how to set up the design system",
        status: "empty",
        content: "",
      },
      {
        id: "page-3",
        title: "Quick Start",
        slug: "quick-start",
        purpose: "Get designers and developers started quickly",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-2",
    title: "Design Tokens",
    slug: "design-tokens",
    pages: [
      {
        id: "page-4",
        title: "Colors",
        slug: "colors",
        purpose: "Document color palette and usage",
        status: "empty",
        content: "",
      },
      {
        id: "page-5",
        title: "Typography",
        slug: "typography",
        purpose: "Document font families, sizes, and weights",
        status: "empty",
        content: "",
      },
      {
        id: "page-6",
        title: "Spacing",
        slug: "spacing",
        purpose: "Document spacing scale and usage",
        status: "empty",
        content: "",
      },
      {
        id: "page-7",
        title: "Shadows & Effects",
        slug: "shadows-effects",
        purpose: "Document elevation and visual effects",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-3",
    title: "Components",
    slug: "components",
    pages: [
      {
        id: "page-8",
        title: "Buttons",
        slug: "buttons",
        purpose: "Document button variants and usage",
        status: "empty",
        content: "",
      },
      {
        id: "page-9",
        title: "Forms",
        slug: "forms",
        purpose: "Document form inputs and validation",
        status: "empty",
        content: "",
      },
      {
        id: "page-10",
        title: "Navigation",
        slug: "navigation",
        purpose: "Document navigation patterns",
        status: "empty",
        content: "",
      },
      {
        id: "page-11",
        title: "Feedback",
        slug: "feedback",
        purpose: "Document alerts, toasts, and modals",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-4",
    title: "Patterns",
    slug: "patterns",
    pages: [
      {
        id: "page-12",
        title: "Layout Patterns",
        slug: "layout-patterns",
        purpose: "Document common page layouts",
        status: "empty",
        content: "",
      },
      {
        id: "page-13",
        title: "Accessibility",
        slug: "accessibility",
        purpose: "Share accessibility guidelines",
        status: "empty",
        content: "",
      },
      {
        id: "page-14",
        title: "Responsive Design",
        slug: "responsive-design",
        purpose: "Document responsive breakpoints and patterns",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-5",
    title: "Resources",
    slug: "resources",
    pages: [
      {
        id: "page-15",
        title: "Figma Library",
        slug: "figma-library",
        purpose: "Link to Figma files and explain usage",
        status: "empty",
        content: "",
      },
      {
        id: "page-16",
        title: "Contributing",
        slug: "contributing",
        purpose: "Explain how to contribute components",
        status: "empty",
        content: "",
      },
    ],
  },
];
