import type { Section } from "../types";

export const frameworkTemplate: Section[] = [
  {
    id: "section-1",
    title: "Introduction",
    slug: "introduction",
    pages: [
      {
        id: "page-1",
        title: "What is this Framework?",
        slug: "what-is-this-framework",
        purpose: "Explain your framework's philosophy and goals",
        status: "empty",
        content: "",
      },
      {
        id: "page-2",
        title: "Key Features",
        slug: "key-features",
        purpose: "Highlight what makes your framework unique",
        status: "empty",
        content: "",
      },
      {
        id: "page-3",
        title: "Comparison",
        slug: "comparison",
        purpose: "Compare with other frameworks honestly",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-2",
    title: "Getting Started",
    slug: "getting-started",
    pages: [
      {
        id: "page-4",
        title: "Installation",
        slug: "installation",
        purpose: "Show how to install the framework",
        status: "empty",
        content: "",
      },
      {
        id: "page-5",
        title: "Create Your First App",
        slug: "create-your-first-app",
        purpose: "Walk through building a simple application",
        status: "empty",
        content: "",
      },
      {
        id: "page-6",
        title: "Project Structure",
        slug: "project-structure",
        purpose: "Explain recommended project organization",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-3",
    title: "Core Concepts",
    slug: "core-concepts",
    pages: [
      {
        id: "page-7",
        title: "Architecture",
        slug: "architecture",
        purpose: "Explain the framework's architecture",
        status: "empty",
        content: "",
      },
      {
        id: "page-8",
        title: "Routing",
        slug: "routing",
        purpose: "Document routing system and patterns",
        status: "empty",
        content: "",
      },
      {
        id: "page-9",
        title: "State Management",
        slug: "state-management",
        purpose: "Explain how to manage application state",
        status: "empty",
        content: "",
      },
      {
        id: "page-10",
        title: "Data Fetching",
        slug: "data-fetching",
        purpose: "Show how to fetch and manage data",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-4",
    title: "API Reference",
    slug: "api-reference",
    pages: [
      {
        id: "page-11",
        title: "Core APIs",
        slug: "core-apis",
        purpose: "Document main framework APIs",
        status: "empty",
        content: "",
      },
      {
        id: "page-12",
        title: "Configuration",
        slug: "configuration",
        purpose: "Document all configuration options",
        status: "empty",
        content: "",
      },
      {
        id: "page-13",
        title: "Hooks/Lifecycle",
        slug: "hooks-lifecycle",
        purpose: "Document lifecycle hooks or similar patterns",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-5",
    title: "Advanced",
    slug: "advanced",
    pages: [
      {
        id: "page-14",
        title: "Performance Optimization",
        slug: "performance-optimization",
        purpose: "Share performance best practices",
        status: "empty",
        content: "",
      },
      {
        id: "page-15",
        title: "Testing",
        slug: "testing",
        purpose: "Show how to test apps built with your framework",
        status: "empty",
        content: "",
      },
      {
        id: "page-16",
        title: "Deployment",
        slug: "deployment",
        purpose: "Guide users through deployment options",
        status: "empty",
        content: "",
      },
    ],
  },
];
