import type { Section } from "../types";

export const libraryTemplate: Section[] = [
  {
    id: "section-1",
    title: "Introduction",
    slug: "introduction",
    pages: [
      {
        id: "page-1",
        title: "Overview",
        slug: "overview",
        purpose: "Explain what your library does and why it exists",
        status: "empty",
        content: "",
      },
      {
        id: "page-2",
        title: "Key Features",
        slug: "key-features",
        purpose: "Highlight the main capabilities and benefits",
        status: "empty",
        content: "",
      },
      {
        id: "page-3",
        title: "When to Use",
        slug: "when-to-use",
        purpose: "Help developers decide if this library fits their needs",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-2",
    title: "Getting Started",
    slug: "getting-started",
    pages: [
      {
        id: "page-4",
        title: "Installation",
        slug: "installation",
        purpose: "Show how to install via npm, yarn, or pnpm",
        status: "empty",
        content: "",
      },
      {
        id: "page-5",
        title: "Quick Start",
        slug: "quick-start",
        purpose: "Get developers up and running in 5 minutes",
        status: "empty",
        content: "",
      },
      {
        id: "page-6",
        title: "Configuration",
        slug: "configuration",
        purpose: "Document available configuration options",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-3",
    title: "Core Concepts",
    slug: "core-concepts",
    pages: [
      {
        id: "page-7",
        title: "Architecture",
        slug: "architecture",
        purpose: "Explain how your library is structured",
        status: "empty",
        content: "",
      },
      {
        id: "page-8",
        title: "Main Concepts",
        slug: "main-concepts",
        purpose: "Introduce key concepts developers need to understand",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-4",
    title: "API Reference",
    slug: "api-reference",
    pages: [
      {
        id: "page-9",
        title: "Functions",
        slug: "functions",
        purpose: "Document all exported functions",
        status: "empty",
        content: "",
      },
      {
        id: "page-10",
        title: "Types",
        slug: "types",
        purpose: "Document TypeScript types and interfaces",
        status: "empty",
        content: "",
      },
      {
        id: "page-11",
        title: "Classes",
        slug: "classes",
        purpose: "Document classes if your library has them",
        status: "empty",
        content: "",
      },
    ],
  },
  {
    id: "section-5",
    title: "Guides",
    slug: "guides",
    pages: [
      {
        id: "page-12",
        title: "Common Use Cases",
        slug: "common-use-cases",
        purpose: "Show real-world examples",
        status: "empty",
        content: "",
      },
      {
        id: "page-13",
        title: "Best Practices",
        slug: "best-practices",
        purpose: "Share recommended patterns and anti-patterns",
        status: "empty",
        content: "",
      },
      {
        id: "page-14",
        title: "Migration Guide",
        slug: "migration-guide",
        purpose: "Help users upgrade between versions",
        status: "empty",
        content: "",
      },
    ],
  },
];
